#!/bin/bash

DIR="/var/www/"
SERVERUSER="www-data"
SERVERADMIN_EMAIL="top@kek.mate"
SSL_ACTIVE=true
SSLCertificateFile="/etc/ssl/certs/ssl-cert-snakeoil.pem"
SSLCertificateKeyFile="/etc/ssl/private/ssl-cert-snakeoil.key"
AUTO_ENABLE_PAGE=true
CREATE_LOCAL_HOSTS=true

read_page_name(){

    echo -n "Name for new Page (without www): "
    read PAGENAME
}

is_user_root(){

    if [ $(id -u) -ne 0 ]
    then 
        echo "Please run the script as root!"
        exit 1
    fi
}

check_project_existing(){

    if [ -d "$DIR$PAGENAME/" ]; then
        echo "Error: Project ${PAGENAME} already existing!"
        exit 2
    else
        echo "Installing config files in ${DIR}${PAGENAME}/ ..."
    fi
}

create_sample_page(){

    touch /var/www/${PAGENAME}/public/index.php
    echo "<html>
    <head>
        <title>$PAGENAME</title>
    </head>
    <body>
        <h1>Success! The $PAGENAME virtual host is working!</h1>
        <d><?php echo "server up and running!"; ?>
           <?php echo "installed on $(date)"; ?>
           <?php echo "Current PHP version: " . phpversion(); ?>
           <?php echo "server version: " . apache_get_version(); ?>
        </d>
    </body>
</html>" >> /var/www/${PAGENAME}/public/index.html
}

create_vhost_file(){

    touch /etc/apache2/sites-available/${PAGENAME}.conf
    echo "<VirtualHost *:80>

    ServerAdmin $SERVERADMIN_EMAIL

    ServerName $PAGENAME
    ServerAlias www.$PAGENAME

    DocumentRoot /var/www/$PAGENAME/public

    <Directory  /var/www/$PAGENAME/public>
        Options Indexes FollowSymlinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /var/www/${PAGENAME}/log/error.log
    CustomLog /var/www/${PAGENAME}/log/access.log combined

</VirtualHost>" >> /etc/apache2/sites-available/${PAGENAME}.conf
}

create_vhost_ssl_file(){

    touch /etc/apache2/sites-available/${PAGENAME}-ssl.conf
    echo "<IfModule mod_ssl.c>
    <VirtualHost _default_:443>

        ServerAdmin $SERVERADMIN_EMAIL

        ServerName $PAGENAME
        ServerAlias www.$PAGENAME

        DocumentRoot /var/www/$PAGENAME/public

        <Directory  /var/www/$PAGENAME/public>
            Options Indexes FollowSymlinks
            AllowOverride All
            Require all granted
        </Directory>


        ErrorLog /var/www/${PAGENAME}/log/error.log
        CustomLog /var/www/${PAGENAME}/log/access.log combined

        SSLEngine on

        SSLCertificateFile $SSLCertificateFile
        SSLCertificateKeyFile $SSLCertificateKeyFile

        <FilesMatch \"\.(cgi|shtml|phtml|php)$\">
                        SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                        SSLOptions +StdEnvVars
        </Directory>

    </VirtualHost>
</IfModule>" >> /etc/apache2/sites-available/${PAGENAME}-ssl.conf
}

create_file_structure(){
    
    mkdir /var/www/${PAGENAME}
    mkdir /var/www/${PAGENAME}/public
    mkdir /var/www/${PAGENAME}/log

    create_sample_page

    chown -R www-data:www-data /var/www/${PAGENAME}
    chmod -R 755 /var/www/${PAGENAME}
    chmod -R 775 /var/www/${PAGENAME}/log
    
}

############################################################################

read_page_name
check_project_existing
is_user_root
create_file_structure
create_vhost_file

if ${SSL_ACTIVE}; then
    create_vhost_ssl_file
fi

if ${AUTO_ENABLE_PAGE}; then
    a2ensite ${PAGENAME}.conf
    if ${SSL_ACTIVE}; then
        a2ensite ${PAGENAME}-ssl.conf
    fi
fi

if ${CREATE_LOCAL_HOSTS}; then
    sed -i "1s/^/127.0.0.1      $PAGENAME\n/" /etc/hosts
fi

nautilus /etc/apache2/sites-enabled/ && nautilus /var/www/${PAGENAME}
systemctl restart apache2